import { AdminRecord, Metric } from "./pagekit";

/* ─── School names (used for dropdown filter) ─── */
export const SCHOOL_NAMES = [
    "Bluebells Public School",
    "St. Xavier's Academy",
    "Green Valley School",
    "Little Stars International",
];

/* ─── School Details (full details for school management) ─── */
export type SchoolDetail = {
    id: string; name: string; admin: string; email: string; phone: string;
    address: string; city: string; state: string; pincode: string;
    plan: string; planExpiry: string; status: string;
    studentCount: number; parentCount: number; busCount: number; driverCount: number;
    registeredOn: string; principal: string; principalPhone: string;
    gstNumber: string; website: string;
};

export const schoolDetails: SchoolDetail[] = [
    { id: "SCH-101", name: "Bluebells Public School", admin: "Rohan Mehta", email: "admin@bluebells.edu.in", phone: "+91 11 2649 8800", address: "Mother Teresa Crescent, New Delhi", city: "New Delhi", state: "Delhi", pincode: "110023", plan: "Enterprise", planExpiry: "31 Mar 2027", status: "active", studentCount: 842, parentCount: 714, busCount: 12, driverCount: 14, registeredOn: "12 Aug 2026", principal: "Dr. Anjali Mathur", principalPhone: "+91 98100 12345", gstNumber: "07AABCB1234C1ZD", website: "www.bluebells.edu.in" },
    { id: "SCH-102", name: "St. Xavier's Academy", admin: "Ananya Singh", email: "transport@stxaviers.ac.in", phone: "+91 124 456 7890", address: "Sector 49, Sohna Road", city: "Gurugram", state: "Haryana", pincode: "122018", plan: "Growth", planExpiry: "10 Feb 2027", status: "active", studentCount: 510, parentCount: 466, busCount: 8, driverCount: 9, registeredOn: "10 Aug 2026", principal: "Fr. Thomas D'Souza", principalPhone: "+91 98765 43210", gstNumber: "06AABCS5678D1ZE", website: "www.stxaviers.ac.in" },
    { id: "SCH-103", name: "Green Valley School", admin: "Amit Sharma", email: "info@greenvalley.in", phone: "+91 120 430 1122", address: "Sector 62, Near IIIT Delhi", city: "Noida", state: "Uttar Pradesh", pincode: "201309", plan: "Pending", planExpiry: "—", status: "pending", studentCount: 328, parentCount: 0, busCount: 6, driverCount: 4, registeredOn: "Awaiting approval", principal: "Mrs. Kavita Rao", principalPhone: "+91 99990 00112", gstNumber: "—", website: "www.greenvalleyschool.in" },
    { id: "SCH-104", name: "Little Stars International", admin: "Priya Kapoor", email: "admin@littlestars.edu", phone: "+91 141 298 4455", address: "C-Scheme, MI Road", city: "Jaipur", state: "Rajasthan", pincode: "302001", plan: "Starter", planExpiry: "Blocked", status: "blocked", studentCount: 214, parentCount: 190, busCount: 4, driverCount: 5, registeredOn: "05 Jul 2026", principal: "Mr. Rajesh Jain", principalPhone: "+91 94140 55667", gstNumber: "08AABCL9012F1ZG", website: "www.littlestars.edu" },
];

export const schoolMetrics: Metric[] = [
    { label: "Total schools", value: 4, icon: "business", color: "#2563EB", note: "1 pending" },
    { label: "Active schools", value: 2, icon: "checkmark-circle", color: "#16A34A" },
    { label: "Blocked schools", value: 1, icon: "ban", color: "#DC2626" },
];

export const schools: AdminRecord[] = [
    {
        id: "SCH-101",
        title: "Bluebells Public School",
        subtitle: "Rohan Mehta · New Delhi",
        status: "active",
        icon: "business",
        phone: "+91 11 2649 8800",
        email: "admin@bluebells.edu.in",
        address: "Mother Teresa Crescent, New Delhi, 110023",
        fields: [
            "📍 Mother Teresa Crescent, New Delhi · PIN: 110023",
            "👤 Principal: Dr. Anjali Mathur (+91 98100 12345)",
            "👥 842 Students · 714 Parents · 12 Buses · 14 Drivers",
            "💳 Enterprise Plan · Expires: 31 Mar 2027",
            "✉️ admin@bluebells.edu.in · 🌐 www.bluebells.edu.in",
            "📄 GST: 07AABCB1234C1ZD · Reg: 12 Aug 2026",
        ],
        details: [
            { label: "School ID", value: "SCH-101", icon: "key-outline" },
            { label: "Campus Address", value: "Mother Teresa Crescent, New Delhi, PIN 110023", icon: "location-outline" },
            { label: "Transport Admin", value: "Rohan Mehta (+91 11 2649 8800)", icon: "person-outline" },
            { label: "Principal", value: "Dr. Anjali Mathur (+91 98100 12345)", icon: "ribbon-outline" },
            { label: "Official Email", value: "admin@bluebells.edu.in", icon: "mail-outline" },
            { label: "Website", value: "www.bluebells.edu.in", icon: "globe-outline" },
            { label: "GST Identification", value: "07AABCB1234C1ZD", icon: "document-text-outline" },
            { label: "Subscription Plan", value: "Enterprise Plan (₹24,999/yr · Exp: 31 Mar 2027)", icon: "card-outline" },
            { label: "Connected Fleet", value: "12 Buses · 14 Drivers · 8 Active Routes", icon: "bus-outline" },
            { label: "Enrolled Riders", value: "842 Students · 714 Registered Parents", icon: "people-outline" },
            { label: "Registration Date", value: "12 August 2026 · Status: Approved & Active", icon: "calendar-outline" },
        ],
    },
    {
        id: "SCH-102",
        title: "St. Xavier's Academy",
        subtitle: "Ananya Singh · Gurugram",
        status: "active",
        icon: "business",
        phone: "+91 124 456 7890",
        email: "transport@stxaviers.ac.in",
        address: "Sector 49, Sohna Road, Gurugram, 122018",
        fields: [
            "📍 Sector 49, Sohna Road, Gurugram · PIN: 122018",
            "👤 Principal: Fr. Thomas D'Souza (+91 98765 43210)",
            "👥 510 Students · 466 Parents · 8 Buses · 9 Drivers",
            "💳 Growth Plan · Expires: 10 Feb 2027",
            "✉️ transport@stxaviers.ac.in · 🌐 www.stxaviers.ac.in",
            "📄 GST: 06AABCS5678D1ZE · Reg: 10 Aug 2026",
        ],
        details: [
            { label: "School ID", value: "SCH-102", icon: "key-outline" },
            { label: "Campus Address", value: "Sector 49, Sohna Road, Gurugram, Haryana, PIN 122018", icon: "location-outline" },
            { label: "Transport Admin", value: "Ananya Singh (+91 124 456 7890)", icon: "person-outline" },
            { label: "Principal", value: "Fr. Thomas D'Souza (+91 98765 43210)", icon: "ribbon-outline" },
            { label: "Official Email", value: "transport@stxaviers.ac.in", icon: "mail-outline" },
            { label: "Website", value: "www.stxaviers.ac.in", icon: "globe-outline" },
            { label: "GST Identification", value: "06AABCS5678D1ZE", icon: "document-text-outline" },
            { label: "Subscription Plan", value: "Growth Plan (₹14,999/yr · Exp: 10 Feb 2027)", icon: "card-outline" },
            { label: "Connected Fleet", value: "8 Buses · 9 Drivers · 6 Active Routes", icon: "bus-outline" },
            { label: "Enrolled Riders", value: "510 Students · 466 Registered Parents", icon: "people-outline" },
            { label: "Registration Date", value: "10 August 2026 · Status: Approved & Active", icon: "calendar-outline" },
        ],
    },
    {
        id: "SCH-103",
        title: "Green Valley School",
        subtitle: "Amit Sharma · Noida",
        status: "pending",
        icon: "business",
        phone: "+91 120 430 1122",
        email: "info@greenvalley.in",
        address: "Sector 62, Near IIIT Delhi, Noida, 201309",
        fields: [
            "📍 Sector 62, Near IIIT Delhi, Noida · PIN: 201309",
            "👤 Principal: Mrs. Kavita Rao (+91 99990 00112)",
            "👥 Registration request · 328 students declared · 6 buses",
            "💳 Plan: Awaiting Approval",
            "✉️ info@greenvalley.in · 🌐 www.greenvalleyschool.in",
            "📄 Documents awaiting admin review",
        ],
        details: [
            { label: "Request ID", value: "SCH-103", icon: "key-outline" },
            { label: "Campus Address", value: "Sector 62, Near IIIT Delhi, Noida, UP, PIN 201309", icon: "location-outline" },
            { label: "Applicant Admin", value: "Amit Sharma (+91 120 430 1122)", icon: "person-outline" },
            { label: "Principal", value: "Mrs. Kavita Rao (+91 99990 00112)", icon: "ribbon-outline" },
            { label: "Official Email", value: "info@greenvalley.in", icon: "mail-outline" },
            { label: "Declared Fleet", value: "6 Buses · 4 Drivers · 328 Students", icon: "bus-outline" },
            { label: "Application Status", value: "Pending Super Admin Verification & Document Check", icon: "time-outline" },
        ],
    },
    {
        id: "SCH-104",
        title: "Little Stars International",
        subtitle: "Priya Kapoor · Jaipur",
        status: "blocked",
        icon: "business",
        phone: "+91 141 298 4455",
        email: "admin@littlestars.edu",
        address: "C-Scheme, MI Road, Jaipur, 302001",
        fields: [
            "📍 C-Scheme, MI Road, Jaipur · PIN: 302001",
            "👤 Principal: Mr. Rajesh Jain (+91 94140 55667)",
            "👥 214 Students · 190 Parents · 4 Buses · 5 Drivers",
            "💳 Starter Plan · Account Blocked by Super Admin",
            "✉️ admin@littlestars.edu · 🌐 www.littlestars.edu",
            "📄 GST: 08AABCL9012F1ZG · Reg: 05 Jul 2026",
        ],
        details: [
            { label: "School ID", value: "SCH-104", icon: "key-outline" },
            { label: "Campus Address", value: "C-Scheme, MI Road, Jaipur, Rajasthan, PIN 302001", icon: "location-outline" },
            { label: "Admin Contact", value: "Priya Kapoor (+91 141 298 4455)", icon: "person-outline" },
            { label: "Principal", value: "Mr. Rajesh Jain (+91 94140 55667)", icon: "ribbon-outline" },
            { label: "Account Status", value: "Temporarily Blocked by Super Admin for Audit", icon: "ban-outline" },
        ],
    },
];

export const parents: AdminRecord[] = [
    {
        id: "PAR-201",
        title: "Neha Verma",
        subtitle: "Bluebells Public School · Aarav Verma",
        status: "active",
        icon: "people",
        phone: "+91 98765 43210",
        email: "neha.verma@gmail.com",
        address: "Flat 402, Tower B, Sector 6, Dwarka, New Delhi",
        fields: [
            "Class 6-A · Bus 101 · Driver Vikram Yadav",
            "Subscription active · Expires 30 Sep 2026 · +91 98765 43210",
        ],
        details: [
            { label: "Parent ID", value: "PAR-201", icon: "key-outline" },
            { label: "Primary Phone", value: "+91 98765 43210", icon: "call-outline" },
            { label: "Email Address", value: "neha.verma@gmail.com", icon: "mail-outline" },
            { label: "Residential Address", value: "Flat 402, Tower B, Sector 6, Dwarka, New Delhi", icon: "home-outline" },
            { label: "Linked Child / Student", value: "Aarav Verma (Class 6-A · Roll 14 · Adm #BB-2026-0401)", icon: "school-outline" },
            { label: "Affiliated School", value: "Bluebells Public School (Mother Teresa Crescent)", icon: "business-outline" },
            { label: "Assigned Bus", value: "Bus 101 (DL 01 AB 1021)", icon: "bus-outline" },
            { label: "Assigned Driver", value: "Vikram Yadav (+91 98108 39381)", icon: "person-outline" },
            { label: "Pickup & Drop Stop", value: "Dwarka Sector 6 Main Gate · Pickup 07:25 AM · Drop 02:40 PM", icon: "location-outline" },
            { label: "Subscription Plan", value: "Growth Plan (₹999/mo · Active · Renews 30 Sep 2026)", icon: "card-outline" },
            { label: "Payment Mode", value: "UPI Auto-pay (GooglePay)", icon: "wallet-outline" },
            { label: "Emergency Contact", value: "Mr. Rajeev Verma (+91 98112 34567 · Father)", icon: "alert-circle-outline" },
        ],
    },
    {
        id: "PAR-202",
        title: "Sanjay Gupta",
        subtitle: "St. Xavier's Academy · Ishita Singh",
        status: "active",
        icon: "people",
        phone: "+91 91027 65934",
        email: "sanjay.gupta@outlook.com",
        address: "House 112, DLF Phase 5, Golf Course Road, Gurugram",
        fields: [
            "Class 9-B · Bus 203 · Driver Rahul Khan",
            "Subscription active · Expires 14 Oct 2026 · +91 91027 65934",
        ],
        details: [
            { label: "Parent ID", value: "PAR-202", icon: "key-outline" },
            { label: "Primary Phone", value: "+91 91027 65934 (Default Login)", icon: "call-outline" },
            { label: "Email Address", value: "sanjay.gupta@outlook.com", icon: "mail-outline" },
            { label: "Residential Address", value: "House 112, DLF Phase 5, Golf Course Road, Gurugram", icon: "home-outline" },
            { label: "Linked Child / Student", value: "Ishita Singh (Class 9-B · Roll 08 · Adm #SX-2026-0180)", icon: "school-outline" },
            { label: "Affiliated School", value: "St. Xavier's Academy (Sector 49, Gurugram)", icon: "business-outline" },
            { label: "Assigned Bus", value: "Bus 203 (HR 26 C 8872)", icon: "bus-outline" },
            { label: "Assigned Driver", value: "Rahul Khan (+91 98990 01122)", icon: "person-outline" },
            { label: "Pickup & Drop Stop", value: "Horizon Center Stop · Pickup 07:35 AM · Drop 02:50 PM", icon: "location-outline" },
            { label: "Subscription Plan", value: "Growth Plan (₹999/mo · Active · Renews 14 Oct 2026)", icon: "card-outline" },
            { label: "Payment Mode", value: "UPI (PhonePe)", icon: "wallet-outline" },
        ],
    },
    {
        id: "PAR-203",
        title: "Meera Joshi",
        subtitle: "Green Valley School · Kabir Joshi",
        status: "blocked",
        icon: "people",
        phone: "+91 99990 00011",
        email: "meera.j@yahoo.com",
        address: "Sector 62, Block C, Noida, UP",
        fields: [
            "Class 4-A · Bus 305 · Driver Arjun Malik",
            "Subscription inactive · +91 99990 00011",
        ],
        details: [
            { label: "Parent ID", value: "PAR-203", icon: "key-outline" },
            { label: "Phone", value: "+91 99990 00011", icon: "call-outline" },
            { label: "Email", value: "meera.j@yahoo.com", icon: "mail-outline" },
            { label: "Address", value: "Sector 62, Block C, Noida, UP", icon: "home-outline" },
            { label: "Linked Child", value: "Kabir Joshi (Class 4-A · Adm #GV-2026-0145)", icon: "school-outline" },
            { label: "School", value: "Green Valley School", icon: "business-outline" },
            { label: "Account Status", value: "Blocked due to fee non-payment", icon: "ban-outline" },
        ],
    },
    {
        id: "PAR-204",
        title: "Rajesh Sharma",
        subtitle: "Bluebells Public School · Priya Sharma",
        status: "active",
        icon: "people",
        phone: "+91 98102 34567",
        email: "rajesh.sharma@tcs.com",
        address: "Pocket B, Sector 13, Rohini, New Delhi",
        fields: [
            "Class 3-B · Bus 102 · Driver Deepak Singh",
            "Subscription active · Expires 15 Nov 2026 · +91 98102 34567",
        ],
        details: [
            { label: "Parent ID", value: "PAR-204", icon: "key-outline" },
            { label: "Phone", value: "+91 98102 34567", icon: "call-outline" },
            { label: "Email", value: "rajesh.sharma@tcs.com", icon: "mail-outline" },
            { label: "Linked Child", value: "Priya Sharma (Class 3-B · Adm #BB-2026-0289)", icon: "school-outline" },
            { label: "Assigned Bus", value: "Bus 102 (DL 01 CD 3456) · Driver Deepak Singh", icon: "bus-outline" },
            { label: "Plan", value: "Starter Plan (₹499/mo · Exp: 15 Nov 2026)", icon: "card-outline" },
        ],
    },
    {
        id: "PAR-205",
        title: "Sunita Kapoor",
        subtitle: "St. Xavier's Academy · Arjun Kapoor",
        status: "active",
        icon: "people",
        phone: "+91 98991 12233",
        email: "sunita.kapoor@gmail.com",
        address: "Vatika City, Sector 49, Sohna Road, Gurugram",
        fields: [
            "Class 7-C · Bus 204 · Driver Suresh Pal",
            "Subscription active · Expires 20 Dec 2026 · +91 98991 12233",
        ],
        details: [
            { label: "Parent ID", value: "PAR-205", icon: "key-outline" },
            { label: "Phone", value: "+91 98991 12233", icon: "call-outline" },
            { label: "Linked Child", value: "Arjun Kapoor (Class 7-C · Adm #SX-2026-0312)", icon: "school-outline" },
            { label: "Assigned Bus", value: "Bus 204 (HR 26 D 9901) · Driver Suresh Pal", icon: "bus-outline" },
            { label: "Plan", value: "Growth Plan (₹999/mo · Exp: 20 Dec 2026)", icon: "card-outline" },
        ],
    },
    {
        id: "PAR-206",
        title: "Vikram Malhotra",
        subtitle: "Little Stars International · Ananya Malhotra",
        status: "blocked",
        icon: "people",
        phone: "+91 94140 55667",
        email: "vikram.m@gmail.com",
        fields: [
            "Class 5-A · Bus 410 · Unassigned",
            "Account blocked · +91 94140 55667",
        ],
        details: [
            { label: "Parent ID", value: "PAR-206", icon: "key-outline" },
            { label: "Phone", value: "+91 94140 55667", icon: "call-outline" },
            { label: "Linked Child", value: "Ananya Malhotra (Class 5-A)", icon: "school-outline" },
            { label: "School", value: "Little Stars International", icon: "business-outline" },
            { label: "Status", value: "Blocked by Super Admin", icon: "ban-outline" },
        ],
    },
    {
        id: "PAR-207",
        title: "Priyanka Das",
        subtitle: "Bluebells Public School · Rohan Das",
        status: "active",
        icon: "people",
        phone: "+91 98711 22334",
        email: "priyanka.das@gmail.com",
        fields: [
            "Class 8-A · Bus 103 · Driver Manoj Kumar",
            "Subscription active · Expires 28 Sep 2026 · +91 98711 22334",
        ],
        details: [
            { label: "Parent ID", value: "PAR-207", icon: "key-outline" },
            { label: "Phone", value: "+91 98711 22334", icon: "call-outline" },
            { label: "Linked Child", value: "Rohan Das (Class 8-A)", icon: "school-outline" },
            { label: "Assigned Bus", value: "Bus 103 · Driver Manoj Kumar", icon: "bus-outline" },
        ],
    },
    {
        id: "PAR-208",
        title: "Amit Tiwari",
        subtitle: "Green Valley School · Shreya Tiwari",
        status: "active",
        icon: "people",
        phone: "+91 99998 87766",
        email: "amit.tiwari@gmail.com",
        fields: [
            "Class 2-B · Bus 306 · Driver Ajay Verma",
            "Subscription active · Expires 05 Oct 2026 · +91 99998 87766",
        ],
        details: [
            { label: "Parent ID", value: "PAR-208", icon: "key-outline" },
            { label: "Phone", value: "+91 99998 87766", icon: "call-outline" },
            { label: "Linked Child", value: "Shreya Tiwari (Class 2-B)", icon: "school-outline" },
            { label: "Assigned Bus", value: "Bus 306 · Driver Ajay Verma", icon: "bus-outline" },
        ],
    },
    {
        id: "PAR-209",
        title: "Deepika Reddy",
        subtitle: "St. Xavier's Academy · Karthik Reddy",
        status: "active",
        icon: "people",
        phone: "+91 98760 01122",
        email: "deepika.r@gmail.com",
        fields: [
            "Class 10-A · Bus 203 · Driver Rahul Khan",
            "Subscription active · Expires 12 Nov 2026 · +91 98760 01122",
        ],
        details: [
            { label: "Parent ID", value: "PAR-209", icon: "key-outline" },
            { label: "Phone", value: "+91 98760 01122", icon: "call-outline" },
            { label: "Linked Child", value: "Karthik Reddy (Class 10-A)", icon: "school-outline" },
        ],
    },
    {
        id: "PAR-210",
        title: "Manish Agarwal",
        subtitle: "Little Stars International · Divya Agarwal",
        status: "inactive",
        icon: "people",
        phone: "+91 94140 99887",
        email: "manish.a@gmail.com",
        fields: [
            "Class 1-A · Bus 411 · Unassigned",
            "Subscription expired · +91 94140 99887",
        ],
        details: [
            { label: "Parent ID", value: "PAR-210", icon: "key-outline" },
            { label: "Phone", value: "+91 94140 99887", icon: "call-outline" },
            { label: "Linked Child", value: "Divya Agarwal (Class 1-A)", icon: "school-outline" },
        ],
    },
    {
        id: "PAR-211",
        title: "Kavita Patel",
        subtitle: "Bluebells Public School · Dev Patel",
        status: "active",
        icon: "people",
        phone: "+91 98105 56677",
        email: "kavita.p@gmail.com",
        fields: [
            "Class 4-C · Bus 101 · Driver Vikram Yadav",
            "Subscription active · Expires 18 Oct 2026 · +91 98105 56677",
        ],
        details: [
            { label: "Parent ID", value: "PAR-211", icon: "key-outline" },
            { label: "Phone", value: "+91 98105 56677", icon: "call-outline" },
            { label: "Linked Child", value: "Dev Patel (Class 4-C)", icon: "school-outline" },
        ],
    },
    {
        id: "PAR-212",
        title: "Ravi Jain",
        subtitle: "St. Xavier's Academy · Neha Jain",
        status: "active",
        icon: "people",
        phone: "+91 98994 45566",
        email: "ravi.jain@gmail.com",
        fields: [
            "Class 6-B · Bus 204 · Driver Suresh Pal",
            "Subscription active · Expires 22 Nov 2026 · +91 98994 45566",
        ],
        details: [
            { label: "Parent ID", value: "PAR-212", icon: "key-outline" },
            { label: "Phone", value: "+91 98994 45566", icon: "call-outline" },
            { label: "Linked Child", value: "Neha Jain (Class 6-B)", icon: "school-outline" },
        ],
    },
];

export const drivers: AdminRecord[] = [
    {
        id: "DRV-301",
        title: "Vikram Yadav",
        subtitle: "Bluebells Public School · Bus 101",
        status: "active",
        icon: "person",
        phone: "+91 98108 39381",
        fields: [
            "+91 98108 39381 · License verified · Police check verified",
            "Route Dwarka Morning · Last GPS just now · 34 km/h",
        ],
        details: [
            { label: "Driver ID", value: "DRV-301", icon: "key-outline" },
            { label: "Phone Number", value: "+91 98108 39381", icon: "call-outline" },
            { label: "Affiliated School", value: "Bluebells Public School", icon: "business-outline" },
            { label: "Assigned Bus", value: "Bus 101 · Plate: DL 01 AB 1021 (Tata Starbus 42-Seater)", icon: "bus-outline" },
            { label: "Assigned Route", value: "Dwarka Morning Route · 8 stops · 42 students", icon: "git-branch-outline" },
            { label: "Driving License", value: "DL-0420180098712 · Heavy Transport Commercial · Valid till Dec 2028", icon: "card-outline" },
            { label: "Police Verification", value: "Verified & Cleared (Delhi Police Ref #PV-8891)", icon: "shield-checkmark-outline" },
            { label: "Experience & Rating", value: "8 Years Commercial Driving · 4.9 ★ (140 ratings)", icon: "star-outline" },
            { label: "Shift Timings", value: "Morning: 07:00 AM - 08:45 AM | Afternoon: 01:45 PM - 03:30 PM", icon: "time-outline" },
            { label: "Live GPS Telemetry", value: "Speed: 34 km/h · Engine: ON · Live GPS sharing active", icon: "navigate-outline" },
            { label: "Blood Group", value: "O+ Positive · Medical fitness certified", icon: "medkit-outline" },
            { label: "Emergency Contact", value: "Sunita Yadav (+91 98108 00011 · Wife)", icon: "alert-circle-outline" },
        ],
    },
    {
        id: "DRV-302",
        title: "Rahul Khan",
        subtitle: "St. Xavier's Academy · Bus 203",
        status: "active",
        icon: "person",
        phone: "+91 98990 01122",
        fields: [
            "+91 98990 01122 · License verified · Documents verified",
            "Route Golf Course Road · Last GPS 1 min ago · 22 km/h",
        ],
        details: [
            { label: "Driver ID", value: "DRV-302", icon: "key-outline" },
            { label: "Phone Number", value: "+91 98990 01122", icon: "call-outline" },
            { label: "Affiliated School", value: "St. Xavier's Academy", icon: "business-outline" },
            { label: "Assigned Bus", value: "Bus 203 · Plate: HR 26 C 8872 (Eicher Skyline 36-Seater)", icon: "bus-outline" },
            { label: "Assigned Route", value: "Golf Course Road Route · 7 stops · 36 students", icon: "git-branch-outline" },
            { label: "Driving License", value: "HR-2620160012345 · Commercial Heavy · Valid till Aug 2027", icon: "card-outline" },
            { label: "Police Verification", value: "Verified & Cleared (Haryana Police)", icon: "shield-checkmark-outline" },
            { label: "Experience & Rating", value: "6 Years Experience · 4.8 ★ (112 ratings)", icon: "star-outline" },
            { label: "Shift Timings", value: "Morning: 07:15 AM - 08:30 AM | Afternoon: 02:00 PM - 03:45 PM", icon: "time-outline" },
            { label: "Live GPS Telemetry", value: "Speed: 22 km/h · Engine: ON · Live GPS sharing active", icon: "navigate-outline" },
        ],
    },
    {
        id: "DRV-303",
        title: "Arjun Malik",
        subtitle: "Green Valley School · Bus 305",
        status: "inactive",
        icon: "person",
        phone: "+91 98981 12233",
        fields: [
            "+91 98981 12233 · Verification pending",
            "Route Sector 62 · Assigned but not sharing GPS",
        ],
        details: [
            { label: "Driver ID", value: "DRV-303", icon: "key-outline" },
            { label: "Phone", value: "+91 98981 12233", icon: "call-outline" },
            { label: "School", value: "Green Valley School", icon: "business-outline" },
            { label: "Assigned Bus", value: "Bus 305 (UP 16 Y 2024)", icon: "bus-outline" },
            { label: "Status", value: "Documents submitted · Pending admin verification", icon: "time-outline" },
        ],
    },
    {
        id: "DRV-304",
        title: "Deepak Singh",
        subtitle: "Bluebells Public School · Bus 102",
        status: "active",
        icon: "person",
        phone: "+91 98104 45566",
        fields: [
            "+91 98104 45566 · License verified · Police check verified",
            "Route Rohini Morning · Last GPS 2 min ago · 28 km/h",
        ],
        details: [
            { label: "Driver ID", value: "DRV-304", icon: "key-outline" },
            { label: "Phone", value: "+91 98104 45566", icon: "call-outline" },
            { label: "School", value: "Bluebells Public School", icon: "business-outline" },
            { label: "Assigned Bus", value: "Bus 102 (DL 01 CD 3456)", icon: "bus-outline" },
            { label: "Route", value: "Rohini Morning Route · 6 stops", icon: "git-branch-outline" },
            { label: "License", value: "DL-0120190087654 · Valid till 2029", icon: "card-outline" },
        ],
    },
    {
        id: "DRV-305",
        title: "Suresh Pal",
        subtitle: "St. Xavier's Academy · Bus 204",
        status: "active",
        icon: "person",
        phone: "+91 98993 34455",
        fields: [
            "+91 98993 34455 · License verified · Documents verified",
            "Route Sohna Road · Last GPS just now · 18 km/h",
        ],
        details: [
            { label: "Driver ID", value: "DRV-305", icon: "key-outline" },
            { label: "Phone", value: "+91 98993 34455", icon: "call-outline" },
            { label: "School", value: "St. Xavier's Academy", icon: "business-outline" },
            { label: "Assigned Bus", value: "Bus 204 (HR 26 D 9901)", icon: "bus-outline" },
            { label: "Route", value: "Sohna Road Morning Route · 6 stops", icon: "git-branch-outline" },
        ],
    },
    {
        id: "DRV-306",
        title: "Manoj Kumar",
        subtitle: "Bluebells Public School · Bus 103",
        status: "active",
        icon: "person",
        phone: "+91 98107 78899",
        fields: [
            "+91 98107 78899 · License verified · Police check verified",
            "Route Vasant Kunj · Last GPS 3 min ago",
        ],
        details: [
            { label: "Driver ID", value: "DRV-306", icon: "key-outline" },
            { label: "Phone", value: "+91 98107 78899", icon: "call-outline" },
            { label: "School", value: "Bluebells Public School", icon: "business-outline" },
            { label: "Assigned Bus", value: "Bus 103 · Vasant Kunj Route", icon: "bus-outline" },
        ],
    },
    {
        id: "DRV-307",
        title: "Ramesh Gupta",
        subtitle: "Little Stars International · Bus 410",
        status: "blocked",
        icon: "person",
        phone: "+91 94140 33445",
        fields: [
            "+91 94140 33445 · License expired · Verification failed",
            "Route Mansarovar · Account blocked",
        ],
        details: [
            { label: "Driver ID", value: "DRV-307", icon: "key-outline" },
            { label: "Phone", value: "+91 94140 33445", icon: "call-outline" },
            { label: "School", value: "Little Stars International", icon: "business-outline" },
            { label: "Status", value: "License expired · Blocked by Super Admin", icon: "ban-outline" },
        ],
    },
    {
        id: "DRV-308",
        title: "Ajay Verma",
        subtitle: "Green Valley School · Bus 306",
        status: "active",
        icon: "person",
        phone: "+91 99992 23344",
        fields: [
            "+91 99992 23344 · License verified · Documents verified",
            "Route Sector 62 Ext. · Last GPS 5 min ago",
        ],
        details: [
            { label: "Driver ID", value: "DRV-308", icon: "key-outline" },
            { label: "Phone", value: "+91 99992 23344", icon: "call-outline" },
            { label: "School", value: "Green Valley School", icon: "business-outline" },
            { label: "Assigned Bus", value: "Bus 306 · Indirapuram Route", icon: "bus-outline" },
        ],
    },
];

export const students: AdminRecord[] = [
    {
        id: "STU-401",
        title: "Aarav Verma",
        subtitle: "Bluebells Public School · Class 6-A",
        status: "active",
        icon: "school",
        fields: [
            "Admission: BB-2026-0401 · Roll 14",
            "Parent Neha Verma · Bus 101 · Driver Vikram Yadav",
        ],
        details: [
            { label: "Student ID", value: "STU-401", icon: "key-outline" },
            { label: "Admission Number", value: "BB-2026-0401", icon: "id-card-outline" },
            { label: "Class & Section", value: "Class 6-A · Roll Number: 14", icon: "school-outline" },
            { label: "Affiliated School", value: "Bluebells Public School (Mother Teresa Crescent)", icon: "business-outline" },
            { label: "Parent / Guardian", value: "Neha Verma (+91 98765 43210 · neha.verma@gmail.com)", icon: "person-outline" },
            { label: "Assigned Bus", value: "Bus 101 · Plate: DL 01 AB 1021", icon: "bus-outline" },
            { label: "Assigned Driver", value: "Vikram Yadav (+91 98108 39381)", icon: "car-outline" },
            { label: "Pickup Stop & Time", value: "Sector 6 Dwarka Gate · Morning 07:25 AM", icon: "location-outline" },
            { label: "Drop Stop & Time", value: "Sector 6 Dwarka Gate · Afternoon 02:40 PM", icon: "location-outline" },
            { label: "Boarding Status", value: "Boarded Bus 101 at 07:28 AM today · Verified via RFID", icon: "checkmark-circle-outline" },
            { label: "Blood Group", value: "B+ Positive", icon: "medkit-outline" },
            { label: "Medical Notes", value: "No known allergies · Fit for sports", icon: "fitness-outline" },
        ],
    },
    {
        id: "STU-402",
        title: "Ishita Singh",
        subtitle: "St. Xavier's Academy · Class 9-B",
        status: "active",
        icon: "school",
        fields: [
            "Admission: SX-2026-0180 · Roll 08",
            "Parent Sanjay Gupta · Bus 203 · Driver Rahul Khan",
        ],
        details: [
            { label: "Student ID", value: "STU-402", icon: "key-outline" },
            { label: "Admission Number", value: "SX-2026-0180", icon: "id-card-outline" },
            { label: "Class & Section", value: "Class 9-B · Roll Number: 08", icon: "school-outline" },
            { label: "School", value: "St. Xavier's Academy (Sector 49, Gurugram)", icon: "business-outline" },
            { label: "Parent / Guardian", value: "Sanjay Gupta (+91 91027 65934)", icon: "person-outline" },
            { label: "Assigned Bus", value: "Bus 203 (HR 26 C 8872) · Driver Rahul Khan", icon: "bus-outline" },
            { label: "Pickup Stop", value: "Horizon Center, DLF Phase 5 · 07:35 AM", icon: "location-outline" },
            { label: "Drop Stop", value: "Horizon Center, DLF Phase 5 · 02:50 PM", icon: "location-outline" },
            { label: "Blood Group", value: "O+ Positive", icon: "medkit-outline" },
        ],
    },
    {
        id: "STU-403",
        title: "Priya Sharma",
        subtitle: "Bluebells Public School · Class 3-B",
        status: "active",
        icon: "school",
        fields: [
            "Admission: BB-2026-0289 · Roll 22",
            "Parent Rajesh Sharma · Bus 102 · Driver Deepak Singh",
        ],
        details: [
            { label: "Student ID", value: "STU-403", icon: "key-outline" },
            { label: "Admission Number", value: "BB-2026-0289", icon: "id-card-outline" },
            { label: "Class & Section", value: "Class 3-B · Roll: 22", icon: "school-outline" },
            { label: "Parent", value: "Rajesh Sharma (+91 98102 34567)", icon: "person-outline" },
            { label: "Bus & Driver", value: "Bus 102 (DL 01 CD 3456) · Driver Deepak Singh", icon: "bus-outline" },
            { label: "Pickup Point", value: "Rohini Sector 13 Stop · 07:20 AM", icon: "location-outline" },
        ],
    },
    {
        id: "STU-404",
        title: "Arjun Kapoor",
        subtitle: "St. Xavier's Academy · Class 7-C",
        status: "active",
        icon: "school",
        fields: [
            "Admission: SX-2026-0312 · Roll 05",
            "Parent Sunita Kapoor · Bus 204 · Driver Suresh Pal",
        ],
        details: [
            { label: "Student ID", value: "STU-404", icon: "key-outline" },
            { label: "Admission Number", value: "SX-2026-0312", icon: "id-card-outline" },
            { label: "Class & Section", value: "Class 7-C · Roll: 05", icon: "school-outline" },
            { label: "Parent", value: "Sunita Kapoor (+91 98991 12233)", icon: "person-outline" },
            { label: "Bus & Driver", value: "Bus 204 (HR 26 D 9901) · Driver Suresh Pal", icon: "bus-outline" },
        ],
    },
    {
        id: "STU-405",
        title: "Kabir Joshi",
        subtitle: "Green Valley School · Class 4-A",
        status: "active",
        icon: "school",
        fields: [
            "Admission: GV-2026-0145 · Roll 11",
            "Parent Meera Joshi · Bus 305 · Driver Arjun Malik",
        ],
        details: [
            { label: "Student ID", value: "STU-405", icon: "key-outline" },
            { label: "Admission Number", value: "GV-2026-0145", icon: "id-card-outline" },
            { label: "Class & Section", value: "Class 4-A · Roll: 11", icon: "school-outline" },
            { label: "Parent", value: "Meera Joshi (+91 99990 00011)", icon: "person-outline" },
            { label: "Bus & Driver", value: "Bus 305 (UP 16 Y 2024) · Driver Arjun Malik", icon: "bus-outline" },
        ],
    },
];

export const buses: AdminRecord[] = [
    {
        id: "BUS-101",
        title: "Bus 101 · DL 01 AB 1021",
        subtitle: "Bluebells Public School · Vikram Yadav",
        status: "running",
        icon: "bus",
        fields: [
            "34 km/h · Dwarka → School Campus · 42 students · 38 parents",
            "GPS just now · Route active · 78% Fuel",
        ],
        details: [
            { label: "Bus Number & ID", value: "Bus 101 · BUS-101", icon: "key-outline" },
            { label: "Registration Plate", value: "DL 01 AB 1021 (Delhi RTO)", icon: "car-outline" },
            { label: "Vehicle Model", value: "Tata Starbus Ultra (42-Seater)", icon: "bus-outline" },
            { label: "Affiliated School", value: "Bluebells Public School", icon: "business-outline" },
            { label: "Assigned Driver", value: "Vikram Yadav (+91 98108 39381)", icon: "person-outline" },
            { label: "Active Route", value: "Dwarka Morning Route (8 stops)", icon: "git-branch-outline" },
            { label: "Occupancy & Capacity", value: "42 Assigned Students · 38 Registered Parents · Full", icon: "people-outline" },
            { label: "Live Telemetry", value: "Speed: 34 km/h · Engine: Running · Updated: Just now", icon: "speedometer-outline" },
            { label: "Fuel / Battery Level", value: "78% Diesel Tank", icon: "water-outline" },
            { label: "Insurance Validity", value: "Valid till 20 Jan 2027 (ICICI Lombard)", icon: "document-text-outline" },
            { label: "Fitness Certificate", value: "Valid till 15 Nov 2027 (Delhi Transport)", icon: "shield-checkmark-outline" },
            { label: "GPS Hardware Device", value: "Teltonika FMB920 · IMEI #864901048291029", icon: "hardware-chip-outline" },
        ],
    },
    {
        id: "BUS-203",
        title: "Bus 203 · HR 26 C 8872",
        subtitle: "St. Xavier's Academy · Rahul Khan",
        status: "running",
        icon: "bus",
        fields: [
            "22 km/h · Golf Course Road → School · 36 students · 31 parents",
            "GPS 1 min ago · Route active · 85% Fuel",
        ],
        details: [
            { label: "Bus Number & ID", value: "Bus 203 · BUS-203", icon: "key-outline" },
            { label: "Registration Plate", value: "HR 26 C 8872 (Gurugram RTO)", icon: "car-outline" },
            { label: "Vehicle Model", value: "Eicher Skyline Pro (36-Seater)", icon: "bus-outline" },
            { label: "School", value: "St. Xavier's Academy", icon: "business-outline" },
            { label: "Driver", value: "Rahul Khan (+91 98990 01122)", icon: "person-outline" },
            { label: "Active Route", value: "Golf Course Road Route (7 stops)", icon: "git-branch-outline" },
            { label: "Telemetry", value: "Speed: 22 km/h · Engine: ON · Live GPS", icon: "navigate-outline" },
            { label: "Insurance", value: "Valid till 14 May 2027", icon: "document-text-outline" },
        ],
    },
    {
        id: "BUS-305",
        title: "Bus 305 · UP 16 Y 2024",
        subtitle: "Green Valley School · Arjun Malik",
        status: "stopped",
        icon: "bus",
        fields: [
            "0 km/h · Sector 62 → School · 28 students · 25 parents",
            "GPS 8 min ago · Waiting at stop · 62% Fuel",
        ],
        details: [
            { label: "Bus Number", value: "Bus 305 · UP 16 Y 2024", icon: "key-outline" },
            { label: "School", value: "Green Valley School", icon: "business-outline" },
            { label: "Driver", value: "Arjun Malik (+91 98981 12233)", icon: "person-outline" },
            { label: "Route", value: "Sector 62 Evening Route (5 stops)", icon: "git-branch-outline" },
            { label: "Status", value: "Stopped at Fortis Chowk · Speed: 0 km/h", icon: "pause-outline" },
        ],
    },
    {
        id: "BUS-410",
        title: "Bus 410 · RJ 14 P 4511",
        subtitle: "Little Stars International · Unassigned",
        status: "offline",
        icon: "bus",
        fields: [
            "0 km/h · Mansarovar → School · 20 students · 18 parents",
            "Last GPS yesterday · Offline",
        ],
        details: [
            { label: "Bus Number", value: "Bus 410 · RJ 14 P 4511", icon: "key-outline" },
            { label: "School", value: "Little Stars International", icon: "business-outline" },
            { label: "Status", value: "Offline · GPS Device Disconnected", icon: "cloud-offline-outline" },
        ],
    },
    {
        id: "BUS-102",
        title: "Bus 102 · DL 01 CD 3456",
        subtitle: "Bluebells Public School · Deepak Singh",
        status: "running",
        icon: "bus",
        fields: [
            "28 km/h · Rohini → School · 38 students · 35 parents",
            "GPS 2 min ago · Route active",
        ],
        details: [
            { label: "Bus Number", value: "Bus 102 · DL 01 CD 3456", icon: "key-outline" },
            { label: "School", value: "Bluebells Public School", icon: "business-outline" },
            { label: "Driver", value: "Deepak Singh (+91 98104 45566)", icon: "person-outline" },
            { label: "Route", value: "Rohini Morning Route · 6 stops", icon: "git-branch-outline" },
        ],
    },
    {
        id: "BUS-204",
        title: "Bus 204 · HR 26 D 9901",
        subtitle: "St. Xavier's Academy · Suresh Pal",
        status: "running",
        icon: "bus",
        fields: [
            "18 km/h · Sohna Road → School · 30 students · 27 parents",
            "GPS just now · Route active",
        ],
        details: [
            { label: "Bus Number", value: "Bus 204 · HR 26 D 9901", icon: "key-outline" },
            { label: "School", value: "St. Xavier's Academy", icon: "business-outline" },
            { label: "Driver", value: "Suresh Pal (+91 98993 34455)", icon: "person-outline" },
            { label: "Route", value: "Sohna Road Morning Route · 6 stops", icon: "git-branch-outline" },
        ],
    },
];

/* ─── Routes across all schools ─── */
export const routes: AdminRecord[] = [
    {
        id: "R-101",
        title: "Dwarka Morning Route",
        subtitle: "Bluebells Public School · Bus 101 · 8 stops",
        status: "active",
        icon: "git-branch",
        fields: [
            "Stops: Sector 6 → Sector 10 → Sector 14 → Bluebells Campus",
            "Driver Vikram Yadav · 42 students assigned · Morning 07:15 AM",
        ],
        details: [
            { label: "Route ID", value: "R-101", icon: "key-outline" },
            { label: "Route Name", value: "Dwarka Morning Shift Express", icon: "git-branch-outline" },
            { label: "School", value: "Bluebells Public School", icon: "business-outline" },
            { label: "Assigned Bus", value: "Bus 101 (DL 01 AB 1021)", icon: "bus-outline" },
            { label: "Assigned Driver", value: "Vikram Yadav (+91 98108 39381)", icon: "person-outline" },
            { label: "Start & End Times", value: "Start: 07:15 AM at Dwarka Sec 6 → Reach: 08:10 AM at School Campus", icon: "time-outline" },
            { label: "Total Stops & Students", value: "8 Stops · 42 Students Assigned · Full Capacity", icon: "location-outline" },
            { label: "Stop List", value: "1. Sec 6 Gate → 2. Sec 10 Market → 3. Sec 12 Metro → 4. Sec 14 DDA → 5. Sec 19 Chowk → 6. Sec 22 → 7. Dwarka Mor → 8. Bluebells Campus", icon: "list-outline" },
        ],
    },
    {
        id: "R-102",
        title: "Rohini Morning Route",
        subtitle: "Bluebells Public School · Bus 102 · 6 stops",
        status: "active",
        icon: "git-branch",
        fields: [
            "Stops: Sector 9 → Sector 13 → Pitampura → Bluebells Campus",
            "Driver Deepak Singh · 38 students assigned · Morning 07:20 AM",
        ],
        details: [
            { label: "Route ID", value: "R-102", icon: "key-outline" },
            { label: "School", value: "Bluebells Public School", icon: "business-outline" },
            { label: "Bus & Driver", value: "Bus 102 (DL 01 CD 3456) · Driver Deepak Singh", icon: "bus-outline" },
            { label: "Stops", value: "6 Stops · 38 Students Assigned", icon: "location-outline" },
        ],
    },
    {
        id: "R-201",
        title: "Golf Course Road Route",
        subtitle: "St. Xavier's Academy · Bus 203 · 7 stops",
        status: "active",
        icon: "git-branch",
        fields: [
            "Stops: Phase 5 → Horizon Center → Sector 49 → Campus",
            "Driver Rahul Khan · 36 students assigned · Morning 07:30 AM",
        ],
        details: [
            { label: "Route ID", value: "R-201", icon: "key-outline" },
            { label: "School", value: "St. Xavier's Academy", icon: "business-outline" },
            { label: "Bus & Driver", value: "Bus 203 (HR 26 C 8872) · Driver Rahul Khan", icon: "bus-outline" },
            { label: "Stops", value: "7 Stops · 36 Students Assigned", icon: "location-outline" },
        ],
    },
    {
        id: "R-202",
        title: "Sohna Road Morning Route",
        subtitle: "St. Xavier's Academy · Bus 204 · 6 stops",
        status: "active",
        icon: "git-branch",
        fields: [
            "Stops: Subhash Chowk → Vatika City → Sector 49 Campus",
            "Driver Suresh Pal · 30 students assigned · Morning 07:25 AM",
        ],
        details: [
            { label: "Route ID", value: "R-202", icon: "key-outline" },
            { label: "School", value: "St. Xavier's Academy", icon: "business-outline" },
            { label: "Bus & Driver", value: "Bus 204 · Driver Suresh Pal", icon: "bus-outline" },
        ],
    },
    {
        id: "R-301",
        title: "Sector 62 Evening Route",
        subtitle: "Green Valley School · Bus 305 · 5 stops",
        status: "inactive",
        icon: "git-branch",
        fields: [
            "Stops: Fortis Chowk → Electronic City → Green Valley Campus",
            "Driver Arjun Malik · 28 students assigned · Evening 02:45 PM",
        ],
        details: [
            { label: "Route ID", value: "R-301", icon: "key-outline" },
            { label: "School", value: "Green Valley School", icon: "business-outline" },
            { label: "Bus & Driver", value: "Bus 305 · Driver Arjun Malik", icon: "bus-outline" },
        ],
    },
    {
        id: "R-302",
        title: "Indirapuram Route",
        subtitle: "Green Valley School · Bus 306 · 6 stops",
        status: "active",
        icon: "git-branch",
        fields: [
            "Stops: Shipra Mall → Ahinsa Khand → Sector 62 Campus",
            "Driver Ajay Verma · 24 students assigned · Morning 07:40 AM",
        ],
        details: [
            { label: "Route ID", value: "R-302", icon: "key-outline" },
            { label: "School", value: "Green Valley School", icon: "business-outline" },
            { label: "Bus & Driver", value: "Bus 306 · Driver Ajay Verma", icon: "bus-outline" },
        ],
    },
    {
        id: "R-401",
        title: "C-Scheme Jaipur Route",
        subtitle: "Little Stars International · Bus 410 · 4 stops",
        status: "inactive",
        icon: "git-branch",
        fields: [
            "Stops: MI Road → Panch Batti → C-Scheme Campus",
            "Driver Ramesh Gupta · 20 students assigned",
        ],
        details: [
            { label: "Route ID", value: "R-401", icon: "key-outline" },
            { label: "School", value: "Little Stars International", icon: "business-outline" },
        ],
    },
    {
        id: "R-402",
        title: "Mansarovar Route",
        subtitle: "Little Stars International · Bus 411 · 5 stops",
        status: "inactive",
        icon: "git-branch",
        fields: [
            "Stops: VT Road → Madhyam Marg → Campus",
            "Unassigned driver · 18 students declared",
        ],
        details: [
            { label: "Route ID", value: "R-402", icon: "key-outline" },
            { label: "School", value: "Little Stars International", icon: "business-outline" },
        ],
    },
];

/* ─── Orders / Subscriptions Transactions ─── */
export type OrderRecord = {
    id: string;
    parentName: string;
    studentName: string;
    schoolName: string;
    amount: string;
    planName: string;
    date: string;
    paymentMode: string;
    status: "paid" | "pending" | "processing" | "refunded";
};

export const orders: OrderRecord[] = [
    { id: "ORD-9821", parentName: "Sanjay Gupta", studentName: "Ishita Singh (Class 9-B)", schoolName: "St. Xavier's Academy", amount: "₹999", planName: "Growth Plan · Monthly", date: "15 Aug 2026, 09:20 AM", paymentMode: "UPI · PhonePe", status: "paid" },
    { id: "ORD-9820", parentName: "Rajesh Sharma", studentName: "Priya Sharma (Class 3-B)", schoolName: "Bluebells Public School", amount: "₹499", planName: "Starter Plan · Monthly", date: "14 Aug 2026, 06:45 PM", paymentMode: "UPI · GooglePay", status: "paid" },
    { id: "ORD-9819", parentName: "Sunita Kapoor", studentName: "Arjun Kapoor (Class 7-C)", schoolName: "St. Xavier's Academy", amount: "₹999", planName: "Growth Plan · Monthly", date: "14 Aug 2026, 02:15 PM", paymentMode: "HDFC Netbanking", status: "paid" },
    { id: "ORD-9818", parentName: "Amit Tiwari", studentName: "Shreya Tiwari (Class 2-B)", schoolName: "Green Valley School", amount: "₹499", planName: "Starter Plan · Monthly", date: "13 Aug 2026, 11:30 AM", paymentMode: "Paytm UPI", status: "pending" },
    { id: "ORD-9817", parentName: "Kavita Patel", studentName: "Dev Patel (Class 4-C)", schoolName: "Bluebells Public School", amount: "₹999", planName: "Growth Plan · Monthly", date: "12 Aug 2026, 04:10 PM", paymentMode: "ICICI Debit Card", status: "paid" },
    { id: "ORD-9816", parentName: "Meera Joshi", studentName: "Kabir Joshi (Class 4-A)", schoolName: "Green Valley School", amount: "₹499", planName: "Starter Plan · Cancelled", date: "10 Aug 2026, 01:05 PM", paymentMode: "UPI · Refund Pending", status: "refunded" },
];

export const payments: AdminRecord[] = [
    {
        id: "PAY-8401",
        title: "WD-20260814-01 · ₹28,400",
        subtitle: "Bluebells Public School · Withdrawal",
        status: "pending",
        icon: "wallet",
        fields: [
            "HDFC bank transfer · ****4482 · Requested 14 Aug 2026",
            "Available balance ₹84,200 · Admin note required",
        ],
        details: [
            { label: "Payout ID", value: "WD-20260814-01", icon: "key-outline" },
            { label: "Requested Amount", value: "₹28,400.00", icon: "cash-outline" },
            { label: "Target Account", value: "HDFC Bank (A/C: *******4482 · IFSC: HDFC0001042)", icon: "card-outline" },
            { label: "Account Holder", value: "Bluebells Public School Society", icon: "business-outline" },
            { label: "Request Timestamp", value: "14 August 2026, 11:45 AM", icon: "time-outline" },
            { label: "Available Net Balance", value: "₹84,200.00", icon: "wallet-outline" },
            { label: "Payout Status", value: "Pending Super Admin Authorization", icon: "alert-circle-outline" },
        ],
    },
    {
        id: "PAY-8402",
        title: "SUB-20260813-92 · ₹999",
        subtitle: "Sanjay Gupta · St. Xavier's Academy",
        status: "completed",
        icon: "card",
        fields: [
            "UPI sanjay@upi · Transaction completed 13 Aug 2026",
            "St. Xavier's Academy · Growth plan",
        ],
        details: [
            { label: "Order ID", value: "SUB-20260813-92", icon: "key-outline" },
            { label: "Amount Paid", value: "₹999.00", icon: "cash-outline" },
            { label: "Parent", value: "Sanjay Gupta (+91 91027 65934)", icon: "person-outline" },
            { label: "Student", value: "Ishita Singh (Class 9-B · St. Xavier's)", icon: "school-outline" },
            { label: "Payment Mode", value: "UPI · VPA: sanjay@okhdfcbank", icon: "wallet-outline" },
            { label: "Bank Ref Number", value: "UPI/322910849201/PAY", icon: "receipt-outline" },
            { label: "Payment Date", value: "13 August 2026, 09:20 AM", icon: "calendar-outline" },
            { label: "Status", value: "Settled & Completed", icon: "checkmark-circle-outline" },
        ],
    },
    {
        id: "PAY-8403",
        title: "WD-20260812-08 · ₹12,600",
        subtitle: "St. Xavier's Academy · Withdrawal",
        status: "processing",
        icon: "wallet",
        fields: [
            "ICICI bank transfer · ****0901 · Requested 12 Aug 2026",
            "Processing by Super Admin",
        ],
        details: [
            { label: "Payout ID", value: "WD-20260812-08", icon: "key-outline" },
            { label: "Amount", value: "₹12,600.00", icon: "cash-outline" },
            { label: "Bank Details", value: "ICICI Bank (A/C: *******0901)", icon: "card-outline" },
            { label: "Status", value: "Bank Processing in Progress", icon: "time-outline" },
        ],
    },
    {
        id: "PAY-8404",
        title: "SUB-20260811-45 · ₹499",
        subtitle: "Rajesh Sharma · Bluebells Public School",
        status: "completed",
        icon: "card",
        fields: [
            "UPI rajesh@upi · Transaction completed 11 Aug 2026",
            "Bluebells Public School · Starter plan",
        ],
        details: [
            { label: "Order ID", value: "SUB-20260811-45", icon: "key-outline" },
            { label: "Amount", value: "₹499.00", icon: "cash-outline" },
            { label: "Parent", value: "Rajesh Sharma (+91 98102 34567)", icon: "person-outline" },
            { label: "Student", value: "Priya Sharma (Class 3-B)", icon: "school-outline" },
        ],
    },
    {
        id: "PAY-8405",
        title: "SUB-20260810-78 · ₹999",
        subtitle: "Sunita Kapoor · St. Xavier's Academy",
        status: "completed",
        icon: "card",
        fields: [
            "UPI sunita@upi · Transaction completed 10 Aug 2026",
            "St. Xavier's Academy · Growth plan",
        ],
        details: [
            { label: "Order ID", value: "SUB-20260810-78", icon: "key-outline" },
            { label: "Amount", value: "₹999.00", icon: "cash-outline" },
            { label: "Parent", value: "Sunita Kapoor (+91 98991 12233)", icon: "person-outline" },
        ],
    },
    {
        id: "PAY-8406",
        title: "WD-20260809-03 · ₹8,200",
        subtitle: "Green Valley School · Withdrawal",
        status: "pending",
        icon: "wallet",
        fields: [
            "SBI bank transfer · ****7712 · Requested 09 Aug 2026",
            "Available balance ₹22,400",
        ],
        details: [
            { label: "Payout ID", value: "WD-20260809-03", icon: "key-outline" },
            { label: "Amount", value: "₹8,200.00", icon: "cash-outline" },
            { label: "School", value: "Green Valley School", icon: "business-outline" },
        ],
    },
    {
        id: "REF-20260810-12",
        title: "Refund · ₹999",
        subtitle: "Meera Joshi · Green Valley School",
        status: "pending",
        icon: "return-down-back",
        fields: [
            "Original payment SUB-20260801-12 · Reason: plan cancellation",
            "UPI meera@upi · Requested 10 Aug 2026",
        ],
        details: [
            { label: "Refund ID", value: "REF-20260810-12", icon: "key-outline" },
            { label: "Refund Amount", value: "₹999.00", icon: "cash-outline" },
            { label: "Parent", value: "Meera Joshi (+91 99990 00011)", icon: "person-outline" },
            { label: "Reason", value: "Parent requested refund due to bus route cancellation", icon: "alert-circle-outline" },
        ],
    },
];

export const subscriptions: AdminRecord[] = [
    {
        id: "SUB-20260813-92",
        title: "Sanjay Gupta · Growth plan",
        subtitle: "Ishita Singh · St. Xavier's Academy",
        status: "active",
        icon: "card",
        fields: [
            "₹999 · Started 13 Aug 2026 · Expires 13 Sep 2026",
            "UPI transaction · Auto-renew enabled",
        ],
        details: [
            { label: "Subscription ID", value: "SUB-20260813-92", icon: "key-outline" },
            { label: "Plan Type", value: "Growth Plan (₹999 / Monthly)", icon: "card-outline" },
            { label: "Subscriber", value: "Sanjay Gupta (+91 91027 65934)", icon: "person-outline" },
            { label: "Student", value: "Ishita Singh (Class 9-B · St. Xavier's)", icon: "school-outline" },
            { label: "Billing Cycle", value: "Monthly (13 Aug 2026 → 13 Sep 2026)", icon: "calendar-outline" },
            { label: "Auto-Renewal", value: "Enabled via UPI Mandate", icon: "checkmark-circle-outline" },
        ],
    },
    {
        id: "SUB-20260801-12",
        title: "Meera Joshi · Starter plan",
        subtitle: "Kabir Joshi · Green Valley School",
        status: "expired",
        icon: "card",
        fields: [
            "₹499 · Started 01 Aug 2026 · Expired 10 Aug 2026",
            "Renewal cancelled by parent",
        ],
        details: [
            { label: "Subscription ID", value: "SUB-20260801-12", icon: "key-outline" },
            { label: "Plan", value: "Starter Plan (₹499)", icon: "card-outline" },
            { label: "Subscriber", value: "Meera Joshi (+91 99990 00011)", icon: "person-outline" },
            { label: "Status", value: "Expired & Cancelled", icon: "ban-outline" },
        ],
    },
    {
        id: "SUB-20260811-45",
        title: "Rajesh Sharma · Starter plan",
        subtitle: "Priya Sharma · Bluebells Public School",
        status: "active",
        icon: "card",
        fields: [
            "₹499 · Started 11 Aug 2026 · Expires 11 Sep 2026",
            "UPI transaction · Auto-renew enabled",
        ],
        details: [
            { label: "Subscription ID", value: "SUB-20260811-45", icon: "key-outline" },
            { label: "Plan", value: "Starter Plan (₹499)", icon: "card-outline" },
            { label: "Subscriber", value: "Rajesh Sharma (+91 98102 34567)", icon: "person-outline" },
        ],
    },
    {
        id: "SUB-20260810-78",
        title: "Sunita Kapoor · Growth plan",
        subtitle: "Arjun Kapoor · St. Xavier's Academy",
        status: "active",
        icon: "card",
        fields: [
            "₹999 · Started 10 Aug 2026 · Expires 10 Sep 2026",
            "UPI transaction · Auto-renew enabled",
        ],
        details: [
            { label: "Subscription ID", value: "SUB-20260810-78", icon: "key-outline" },
            { label: "Plan", value: "Growth Plan (₹999)", icon: "card-outline" },
            { label: "Subscriber", value: "Sunita Kapoor (+91 98991 12233)", icon: "person-outline" },
        ],
    },
];
