import React, { useState } from "react";
import { Alert, Modal, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { AdminPageFrame, SchoolFilterBar, styles, COLORS, FONT } from "./pagekit";
import { SCHOOL_NAMES, schoolDetails, payments, buses } from "./mockData";

export default function ReportsPage() {
  const [schoolFilter, setSchoolFilter] = useState("All Schools");

  // Export Modal state
  const [exportModalVisible, setExportModalVisible] = useState(false);
  const [exportType, setExportType] = useState<"csv" | "pdf">("csv");
  const [exportData, setExportData] = useState({ title: "", content: "", filename: "" });

  const revenueData: Record<string, { total: string; numeric: number; bars: number[] }> = {
    "All Schools": { total: "₹3,84,920", numeric: 384920, bars: [42, 56, 49, 68, 62, 86, 74] },
    "Bluebells Public School": { total: "₹1,84,200", numeric: 184200, bars: [20, 28, 25, 34, 30, 42, 38] },
    "St. Xavier's Academy": { total: "₹1,42,800", numeric: 142800, bars: [15, 20, 18, 24, 22, 32, 28] },
    "Green Valley School": { total: "₹42,120", numeric: 42120, bars: [5, 6, 4, 8, 7, 9, 6] },
    "Little Stars International": { total: "₹15,800", numeric: 15800, bars: [2, 2, 2, 2, 3, 3, 2] },
  };

  const currentRevenue = revenueData[schoolFilter] ?? revenueData["All Schools"];

  // 1. Generate CSV Data String
  const generateCSV = () => {
    const headers = "School Name,City,State,PIN,Students,Parents,Buses,Drivers,Plan,Status,Revenue\n";
    const rows = schoolDetails
      .filter((s) => schoolFilter === "All Schools" || s.name.toLowerCase().includes(schoolFilter.toLowerCase()))
      .map((s) => {
        const rev = revenueData[s.name]?.total ?? "₹0";
        return `"${s.name}","${s.city}","${s.state}","${s.pincode}",${s.studentCount},${s.parentCount},${s.busCount},${s.driverCount},"${s.plan}","${s.status}","${rev}"`;
      })
      .join("\n");

    const content = `${headers}${rows}\n\n---\nReport Filter: ${schoolFilter}\nTotal Revenue: ${currentRevenue.total}\nGenerated: ${new Date().toLocaleString()}\nExported from: TrackIQ Super Admin`;
    const filename = `TrackIQ_Operations_Report_${schoolFilter.replace(/[^a-zA-Z0-9]/g, "_")}.csv`;

    setExportType("csv");
    setExportData({ title: "CSV Data Export Ready", content, filename });
    setExportModalVisible(true);
  };

  // 2. Generate Formatted PDF / Document Summary
  const generatePDF = () => {
    const dateStr = new Date().toLocaleDateString("en-IN", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });

    const activeSchools = schoolDetails.filter(
      (s) => schoolFilter === "All Schools" || s.name.toLowerCase().includes(schoolFilter.toLowerCase())
    );

    const totalStudents = activeSchools.reduce((acc, curr) => acc + curr.studentCount, 0);
    const totalParents = activeSchools.reduce((acc, curr) => acc + curr.parentCount, 0);
    const totalBuses = activeSchools.reduce((acc, curr) => acc + curr.busCount, 0);

    const content = `=====================================================
  TRACKIQ SUPER ADMIN — EXECUTIVE OPERATIONS REPORT
=====================================================
Date of Generation: ${dateStr}
Target Filter: ${schoolFilter}
Generated By: Super Admin Master (+91 98267 51348)
System Status: 100% Online · All GPS Services Healthy

-----------------------------------------------------
1. FINANCIAL & SUBSCRIPTION SUMMARY
-----------------------------------------------------
• Total Network Revenue: ${currentRevenue.total}
• Monthly Growth Rate: +14.8% MoM
• Active Subscribed Parents: ${totalParents.toLocaleString()}
• Pending Payout Queue: ₹41,000 (2 requests)

-----------------------------------------------------
2. NETWORK & FLEET METRICS
-----------------------------------------------------
• Affiliated Schools: ${activeSchools.length}
• Total Enrolled Students: ${totalStudents.toLocaleString()}
• Total Connected Fleet: ${totalBuses} Buses (${buses.filter((b) => b.status === "running").length} Running Live)
• Fleet On-Time Efficiency: 94.2%

-----------------------------------------------------
3. SCHOOL-BY-SCHOOL BREAKDOWN
-----------------------------------------------------
${activeSchools
  .map(
    (s, i) =>
      `[${i + 1}] ${s.name} (${s.city}, ${s.state})
     - Principal: ${s.principal} (${s.principalPhone})
     - Students: ${s.studentCount} | Parents: ${s.parentCount}
     - Fleet: ${s.busCount} Buses | Drivers: ${s.driverCount}
     - Plan: ${s.plan} (Exp: ${s.planExpiry})
     - Status: ${s.status.toUpperCase()}`
  )
  .join("\n\n")}

=====================================================
End of Report · TrackIQ Cloud Platform · Verified Secure
=====================================================`;

    const filename = `TrackIQ_Executive_Report_${schoolFilter.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`;

    setExportType("pdf");
    setExportData({ title: "Executive Report (PDF / DOC) Ready", content, filename });
    setExportModalVisible(true);
  };

  // 3. Share File via Native OS Dialog
  const handleNativeShare = async () => {
    try {
      await Share.share({
        title: exportData.filename,
        message: exportData.content,
      });
    } catch (err) {
      Alert.alert("Share Failed", "Could not open share dialog.");
    }
  };

  return (
    <AdminPageFrame
      title="Reports & Analytics"
      subtitle="School registrations, bus usage, revenue and subscription analytics."
      actionLabel="Export CSV"
      onAction={generateCSV}
      metrics={[
        { label: "Total revenue", value: currentRevenue.total, icon: "cash", color: "#0F766E" },
        { label: "Fleet efficiency", value: "94%", icon: "bus", color: "#16A34A" },
        { label: "Active parents", value: schoolFilter === "All Schools" ? "2,176" : "714", icon: "people", color: "#7C3AED" },
        { label: "Withdrawals", value: "₹41,000", icon: "wallet", color: "#EA580C" },
      ]}
    >
      {/* ── School filter selector ── */}
      <SchoolFilterBar
        schools={SCHOOL_NAMES}
        selected={schoolFilter}
        onSelect={setSchoolFilter}
      />

      {/* ── Monthly Revenue Chart Box ── */}
      <View style={styles.chart}>
        <View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}>
          <View>
            <Text style={styles.cardTitle}>Monthly Revenue Trend</Text>
            <Text style={styles.cardSubtitle}>{schoolFilter}</Text>
          </View>
          <View style={{ backgroundColor: "#ECFDF3", paddingHorizontal: 7, paddingVertical: 3, borderRadius: 6 }}>
            <Text style={{ color: "#16A34A", fontFamily: "Inter-Bold", fontSize: 9.5 }}>+14.8% GROWTH</Text>
          </View>
        </View>

        <Text style={styles.chartValue}>{currentRevenue.total}</Text>

        <View style={styles.bars}>
          {currentRevenue.bars.map((height, index) => (
            <View key={index} style={styles.barColumn}>
              <View style={[styles.bar, { height: height * 1.1 }]} />
              <Text style={styles.barLabel}>{["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"][index]}</Text>
            </View>
          ))}
        </View>
      </View>

      {/* ── Export Action Buttons ── */}
      <View style={{ flexDirection: "row", gap: 8, marginTop: 10 }}>
        <Pressable
          onPress={generatePDF}
          style={({ pressed }) => [
            styles.outline,
            { flex: 1, justifyContent: "center", minHeight: 44, borderRadius: 12, backgroundColor: "#EEF2FF", borderColor: "#C7D2FE" },
            pressed && { opacity: 0.8 },
          ]}
        >
          <Ionicons name="document-text" size={16} color={COLORS.blue} />
          <Text style={[styles.outlineText, { color: COLORS.blue, fontSize: 11 }]}>Export PDF Report</Text>
        </Pressable>

        <Pressable
          onPress={generateCSV}
          style={({ pressed }) => [
            styles.outline,
            { flex: 1, justifyContent: "center", minHeight: 44, borderRadius: 12, backgroundColor: "#FFF8DB", borderColor: "#FFE066" },
            pressed && { opacity: 0.8 },
          ]}
        >
          <Ionicons name="download" size={16} color={COLORS.gold} />
          <Text style={[styles.outlineText, { color: "#765900", fontSize: 11 }]}>Export CSV Data</Text>
        </Pressable>
      </View>

      {/* ── Export Preview & Share Modal ── */}
      <Modal
        visible={exportModalVisible}
        transparent
        animationType="slide"
        onRequestClose={() => setExportModalVisible(false)}
      >
        <View style={styles.sheetBackdrop}>
          <View style={[styles.sheet, { maxHeight: "88%" }]}>
            <View style={styles.sheetHandle} />
            <View style={styles.sheetHeader}>
              <View
                style={[
                  styles.recordIcon,
                  {
                    backgroundColor: exportType === "pdf" ? "#EEF2FF" : "#FFF8DB",
                    width: 38,
                    height: 38,
                    borderRadius: 12,
                  },
                ]}
              >
                <Ionicons
                  name={exportType === "pdf" ? "document-text" : "grid"}
                  size={20}
                  color={exportType === "pdf" ? COLORS.blue : COLORS.gold}
                />
              </View>
              <View style={{ flex: 1, marginLeft: 10, minWidth: 0 }}>
                <Text style={styles.eyebrow}>
                  {exportType === "pdf" ? "EXECUTIVE PDF / DOC REPORT" : "SPREADSHEET CSV EXPORT"}
                </Text>
                <Text style={styles.sheetTitle} numberOfLines={1}>
                  {exportData.filename}
                </Text>
              </View>
              <Pressable onPress={() => setExportModalVisible(false)}>
                <Ionicons name="close-circle" size={24} color={COLORS.faint} />
              </Pressable>
            </View>

            {/* Content Preview Box */}
            <View style={exp.previewContainer}>
              <View style={exp.previewHeader}>
                <Text style={exp.previewLabel}>EXPORT PREVIEW ({exportType.toUpperCase()})</Text>
                <View style={exp.previewBadge}>
                  <Text style={exp.previewBadgeText}>
                    {Math.round(exportData.content.length / 1024 * 10) / 10} KB
                  </Text>
                </View>
              </View>
              <ScrollView showsVerticalScrollIndicator style={exp.previewScroll}>
                <Text style={exp.previewCode}>{exportData.content}</Text>
              </ScrollView>
            </View>

            {/* Actions */}
            <View style={exp.actionRow}>
              <Pressable
                onPress={handleNativeShare}
                style={({ pressed }) => [exp.shareBtn, pressed && { opacity: 0.85 }]}
              >
                <Ionicons name="share-social" size={17} color="#FFFFFF" />
                <Text style={exp.shareBtnText}>Share / Save File (WhatsApp, Drive, Files)</Text>
              </Pressable>

              <Pressable
                onPress={() => {
                  Alert.alert("Downloaded", `${exportData.filename} has been saved to your local storage.`);
                  setExportModalVisible(false);
                }}
                style={({ pressed }) => [exp.saveBtn, pressed && { opacity: 0.85 }]}
              >
                <Ionicons name="checkmark-done" size={16} color={COLORS.ink} />
                <Text style={exp.saveBtnText}>Save to Device</Text>
              </Pressable>
            </View>
          </View>
        </View>
      </Modal>
    </AdminPageFrame>
  );
}

const exp = StyleSheet.create({
  previewContainer: {
    backgroundColor: "#1E293B",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#334155",
    padding: 12,
    flex: 1,
    marginBottom: 12,
  },
  previewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#334155",
  },
  previewLabel: { color: "#94A3B8", fontFamily: FONT.bold, fontSize: 9, letterSpacing: 0.6 },
  previewBadge: { backgroundColor: "#334155", paddingHorizontal: 6, paddingVertical: 2, borderRadius: 5 },
  previewBadgeText: { color: "#E2E8F0", fontFamily: FONT.bold, fontSize: 8.5 },
  previewScroll: { maxHeight: 220 },
  previewCode: {
    color: "#E2E8F0",
    fontFamily: "monospace",
    fontSize: 10,
    lineHeight: 15,
  },

  actionRow: { gap: 8 },
  shareBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#172554",
    borderRadius: 12,
    paddingVertical: 12,
  },
  shareBtnText: { color: "#FFFFFF", fontFamily: FONT.bold, fontSize: 12 },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#FFD60A",
    borderRadius: 12,
    paddingVertical: 11,
  },
  saveBtnText: { color: "#101828", fontFamily: FONT.bold, fontSize: 12 },
});
